### ISSUE TITLE
我运行一条下载地址，但是aria2c没有反应

### ISSUE THREAD

**Issue by eee-du** [Chion82/xunlei_share#2]
我先是 `xunleishare 'thunder://QUFlZDJrOi8vfGZpbGV8JUU4JUFGJTg5JUU4JUFFJUJDJUU1JThGJThDJUU5JTlCJTg0LlN1aXRzLlMwNEUxNi4lRTQlQjglQUQlRTglOEIlQjElRTUlQUQlOTclRTUlQjklOTUuSFItSERUVi5BQzMuMTAyNFg1NzYueDI2NC5lbmQubWt2fDUzNDMzMDM3OHxiYTE2YzllOWQ5OThjYTcxNDM4ZjgwMjc4YTYyNWRmY3xoPWRyYjRrcHBweXRpeDZyZ3pweHdmNWFtMzdheGVkZnp5fC9aWg=='`
然后生成了xunlei_output ，不管是运行output这个文件还是打开这个文件 在终端中输入生成的指令`aria2c -c -s10 -x10 --header "Cookie: gdriveid=601902F2D83C9A97ED4E6FAC83FA4010;" -o "诉讼双雄.Suits.S04E16.中英字幕.HR-HDTV.AC3.1024X576.x264.end.mkv" "http://gdl.lixian.vip.xunlei.com/download?fid=KodNsIVVQ0TmGYghUZ5ax9FGRisKPNkfAAAAAKvknBRenBiE4AA3jd1EC2+mFIpc&mid=666&threshold=150&tid=5ECC129E58AE04EC50DC439A77B4CA08&srcid=4&verno=1&g=ABE49C145E9C1884E000378DDD440B6FA6148A5C&scn=t37&i=BA16C9E9D998CA71438F80278A625DFC&t=4&ui=208115253&ti=1310424386510080&s=534330378&m=0&n=01AAEE2F90CBABD0DB4F62913674732E535105A16E362ED6D0B2933389C4BB2E48331CAC1B54562E412202CA6E303234585406D271783236344F548A3B2E6D6B76&ff=0&co=B6787CD4A79052EC2F6DBE7BBD6D7324&cm=1&pk=lixian&ak=1:0:6:3&e=1468125549&ms=10485760&ck=601902F2D83C9A97ED4E6FAC83FA4010&at=2E7A8B2D2EB72FCEE22C0F0FF019DB21"`   都没有什么反应

**Comment by Chion82** [comment]
要先安装aria2哦

**Comment by eee-du** [comment]
我安装了 aria2c 的  在web前端上 看不到下载 后台也没有下载

**Comment by Chion82** [comment]
这个只是aria2的CLI下载命令，没有调用aria2 RPC，在web前端是看不到的。直接运行aria2c下载命令就可以了

**Comment by eee-du** [comment]
我运行 aria2c -c -s10 -x10 --header "Cookie: 省略;" -o "省略.mkv" "http://gdl.lixian.vip.xunlei.com/省略"  终端没有任何反映。。

**Comment by Chion82** [comment]
试试运行

```
aria2c --version
```

看看是否能正确输出aria2版本信息？aria2可能没有正确安装

**Comment by eee-du** [comment]
aria2 version 1.19.0

**Comment by Chion82** [comment]
去掉几个参数，试试运行：

```
 aria2c  --header "Cookie: 省略;" -o "省略.mkv" "http://gdl.lixian.vip.xunlei.com/省略" 
```

**Comment by eee-du** [comment]
也是一样 终端没有任何反映 就直接换行等待输入指令了。。。。

**Comment by Chion82** [comment]
虽然不知道是怎么回事。。。但是试试重新安装aria2吧。。。

**Comment by fanyer** [comment]
@evindu @Chion82   cause aria2.conf exists and take effect in your computer ,as a result it won't work under direct-download mode. if you remove the aria2.conf , you'd see the download process bar again.
all what i said is under ubuntu 14.04 and OSX 10.11, while windows is another case

**Comment by lssb** [comment]
qing wen jie jue le ma ?  

buhao yisi
