### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by magicknight** [Chion82/xunlei_share#3]
xunleishare thunder://QUFmdHA6Ly9kczpkc0BkNC4ydHUuY2M6MjAwNjQvW9G4wNfPwtTYd3d3LnhpYW1wNC5jb21dvKvSu7DgNC0zMS5tcDRaWg== 
输入验证码:
Please enter verify code:
emcw
未知错误
Unknown error.

**Comment by Chion82** [comment]
@magicknight 服务端log: 该资源被举报，无法添加到离线空间[0975]
不要下载黄黄的东西哦

**Comment by magicknight** [comment]
噢噢，了解。。   0_0  不过这个是电视剧，终极一班4 的第31集。。。。

**Comment by SunskyXH** [comment]
我下小电影的时候就没事呀（

**Comment by langker** [comment]
我下小电影的时候就没事呀（

**Comment by Chion82** [comment]
@SunskyXH @langker 那你好厉害哦.jpg
