### ISSUE TITLE
好像不work了。

### ISSUE THREAD

**Issue by magicknight** [Chion82/xunlei_share#4]
提交了几个下载都是下面这样的。

xunleishare thunder://QUFlZDJrOi8vfGZpbGV8JUU1JUJGJThEJUU4JTgwJTg1JUU3JUE1JTlFJUU5JUJFJTlGMiVFRiVCQyU5QSVFNyVBMCVCNCVFNSVCRCVCMSVFOCU4MCU4QyVFNSU4NyVCQS5CRDEyODAlRTglQjYlODUlRTYlQjglODUlRTQlQjglQUQlRTglOEIlQjElRTUlOEYlOEMlRTUlQUQlOTcubXA0fDI0OTQxNTE0MjJ8MzA5OEVBMzgwOUYwQjg4MDFEQkE2QkVDQ0ZBRDNFRkN8aD0yWVZYV1M0TjU1SEdDWldFV0dPR0tXMkVHNTJLR0ZaSHwvWlo=
输入验证码:
Please enter verify code:
agv9
提交任务失败，请重试
Failed to commit download task. Please retry.
ERR_MSG=提交失败，请重新输入验证码重试。

**Comment by Chion82** [comment]
离线网页版加了新的验证机制，这个项目暂时不维护了
